version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: meusegredo
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: mymoney
            schema: public
            user: mymoney
            password: 098098pg
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: false