version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: teste
        databases:
          default:
            connector: postgres
            host: http://192.168.0.12:4201
            database: mymoney
            schema: database
            user: postgres
            password: 098098pg
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: false